name: rozklad_knu_fit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  url_launcher: ^6.1.2
  clipboard: ^0.1.3
  fluttertoast: ^8.0.9
  flutter_expanded_tile: ^0.3.6
  connectivity_plus: ^2.0.2
  flutter_native_splash: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  linter: ^1.24.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/schedule.png"

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/icon/

linter:
  rules:
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty